spring:
  session:
    store-type: jdbc
  profiles:
    include: oauth
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  packages-to-scan: badukegg.hackathon.hackathon
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui-hackathon.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
